import { GameCardProps } from 'components/molecules/GameCard/GameCard';

const gameCardItems: GameCardProps[] = [
  {
    id: '1',
    title: 'God of War: Ragnarök',
    genre: 'Action-adventure ',
    developer: 'Santa Monica Games',
    year: '2022',
    img: 'https://i.pinimg.com/originals/34/f8/e5/34f8e55845212171e8bb35edc5b08018.jpg',
    price: '$ 60.99',
    score: 5.0,
    platform: ['playstation'],
    slug: '',
    primaryColor: '#9db4d0',
  },
  {
    id: '2',
    title: 'Star Wars Jedi: Fallen Order',
    genre: 'Action-adventure ',
    developer: 'EA',
    year: '2019',
    img: 'https://cdn2.steamgriddb.com/file/sgdb-cdn/grid/935a281a70ae21d54479c9c468145f7e.png',
    price: '$ 30.00',
    score: 3.8,
    platform: ['playstation', 'pc', 'xbox'],
    slug: '',
    primaryColor: '#a8b6cb',
  },
  {
    id: '3',
    title: 'Cyberpunk 2077',
    genre: 'Action-adventure ',
    developer: 'CD PROJEKT RED',
    year: '2020',
    img: 'https://whatifgaming.com/wp-content/uploads/2022/05/Neon-Aesthetic.jpg',
    price: '$ 10.00',
    score: 1.8,
    platform: ['playstation', 'pc', 'xbox'],
    slug: '',
    primaryColor: '#dabbde',
  },
  {
    id: '4',
    title: 'The Last of Us Part II',
    genre: 'Action-adventure ',
    developer: 'Naughty Dog',
    year: '2020',
    img: 'https://www.jeuxvideo-live.com/wp-content/uploads/jvl/2022/07/le-multi-de-the-last-of-us-2-deevoile-quelques-secrets-de-conception-104207-large.jpg',
    price: '$ 60.99',
    score: 5.0,
    platform: ['playstation'],
    slug: '',
    primaryColor: '#b2a7a5',
  },
  {
    id: '5',
    title: 'Elden Ring',
    genre: 'Action-adventure ',
    developer: 'BANDAI NAMCO Entertainment Inc',
    year: '2022',
    img: 'https://image.api.playstation.com/vulcan/ap/rnd/202110/2000/aGhopp3MHppi7kooGE2Dtt8C.png',
    price: '$ 60.99',
    score: 4.8,
    platform: ['playstation'],
    slug: '',
    primaryColor: '#aeb195',
  },
  {
    id: '6',
    title: 'Horizon Forbidden West',
    genre: 'Action-adventure ',
    developer: 'Santa Monica Games',
    year: '2022',
    img: 'https://t.ctcdn.com.br/efyy2ADqd67kPvUfXBVJWMJiX_I=/1400x788/smart/filters:format(webp)/i499600.png',
    price: '$ 60.99',
    score: 4.8,
    platform: ['playstation'],
    slug: '',
    primaryColor: '#aeb1d2',
  },
  {
    id: '7',
    title: "Marvel's Spider-Man",
    genre: 'Action-adventure ',
    developer: 'Insomniac Games',
    year: '2018',
    img: 'https://image.api.playstation.com/vulcan/ap/rnd/202008/1020/b0OfuUs4lHGWG4VNlHcXwL5a.jpg',
    price: '$ 60.99',
    score: 4.7,
    platform: ['playstation', 'pc'],
    slug: '',
    primaryColor: '#9ab3c5',
  },
  {
    id: '8',
    title: 'The Witcher 3',
    genre: 'Action-adventure ',
    developer: 'CD PROJEKT SA',
    year: '2015',
    img: 'https://e.snmc.io/lk/f/x/1508cc32995d91b6206ee1b1e82b9338/8329790',
    price: '$ 60.99',
    score: 4.5,
    platform: ['playstation', 'pc', 'xbox'],
    slug: '',
    primaryColor: '#d1b2a3',
  },
];

export default gameCardItems;
